name: Profile Stack
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  profile-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate profile stack
        uses: gleich/profile_stack@v2.1.0

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update profile stack"
          file_pattern: "profile-stack.png"
